{
  "name" : "Continuous Integration",
  "on" : {
    "push" : {
      "paths" : [
        "**.c",
        "**.h",
        "**.cpp",
        "**.hpp",
        "**.build",
        "**.in",
        "**.yml",
        "**.gradle",
        "CMakeLists.txt"
      ]
    },
    "pull_request" : {
      "paths" : [
        "**.c",
        "**.h",
        "**.cpp",
        "**.hpp",
        "**.build",
        "**.in",
        "**.yml",
        "**.gradle",
        "CMakeLists.txt"
      ]
    }
  },
  "env" : {
    "CMAKE_GENERATOR" : "Ninja"
  },
  "jobs" : {
    "build-ubuntu" : {
      "runs-on" : "ubuntu-20.04",
      "timeout-minutes" : 20,
      "steps" : [
        {
          "uses" : "actions/checkout@v2",
          "with" : {
            "submodules" : "recursive"
          }
        },
        {
          "run" : "sudo apt-get update"
        },
        {
          "run" : "sudo apt-get install build-essential"
        },
        {
          "uses" : "actions/setup-python@v1",
          "with" : {
            "python-version" : "3.x"
          }
        },
        {
          "uses" : "actions/cache@v1",
          "with" : {
            "path" : "~/.cache/pip",
            "key" : "${{ runner.os }}-pip",
            "restore-keys" : "${{ runner.os }}-pip"
          }
        },
        {
          "run" : "python -m pip install --upgrade ninja"
        },
        {
          "run" : "cmake -S . -B build"
        },
        {
          "run" : "cmake --build build"
        },
        {
          "uses" : "actions/upload-artifact@master",
          "with" : {
            "name" : "dsnet-ubuntu",
            "path" : "build/ds*"
          }
        }
      ]
    },
    "create-release" : {
      "needs" : ["build-ubuntu"],
      "runs-on" : "ubuntu-20.04",
      "timeout-minutes" : 20,
      "if" : "github.ref == 'refs/heads/main'",
      "steps" : [
        {
          "name" : "Download ubuntu artifact",
          "uses" : "actions/download-artifact@v1",
          "with" : {
            "name" : "dsnet-ubuntu"
          }
        },
        {
          "name" : "Prepare artifacts for release",
          "run" : "7z a -tzip dsnet-ubuntu.zip dsnet-ubuntu/*"
        },
        {
          "name" : "Create prerelease",
          "if" : "github.ref == 'refs/heads/main'",
          "uses" : "marvinpinto/action-automatic-releases@latest",
          "with" : {
            "repo_token" : "${{ secrets.GITHUB_TOKEN }}",
            "prerelease" : "true",
            "automatic_release_tag" : "latest",
            "title" : "Latest development builds",
            "files" : "dsnet-ubuntu.zip"
          }
        }
      ]
    }
  }
}
